### ISSUE TITLE
dependency check fails on macos

### ISSUE THREAD

**Issue by nkapila6** [TkinterEP/python-tkextrafont#14]
Hello

When using `pip` to install `tkextrafont`, the installer fails since it seems to check for a dependency. But the command seems to be a `pacman` command which means it thinks I'm on a Linux distro using the `pacman` pm?

Can it be made compatible with macOS?

Here's the full log.
```terminal
 pip install tkextrafont                                                                      ─╯
Collecting tkextrafont
  Using cached tkextrafont-0.6.1.tar.gz (656 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Installing dependency cmake... Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/r0/y9xhb62929x15dw9vm3ztrqr0000gn/T/pip-install-1jbcudj6/tkextrafont_1faf2b91977942949567e5cc73a8a3e9/setup.py", line 63, in <module>
          sp.call(["pacman", "--needed", "--noconfirm", "-S", "mingw-w64-x86_64-{}".format(dep)])  # , stdout=sp.PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/redacted/miniconda3/envs/throwaway/lib/python3.11/subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/redacted/miniconda3/envs/throwaway/lib/python3.11/subprocess.py", line 1022, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Users/redacted/miniconda3/envs/throwaway/lib/python3.11/subprocess.py", line 1899, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'pacman'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by rdbende** [comment]
There will be a new release hopefully within a week, that will fix this, and other issues related to the build system.

**Comment by themetzmeier** [comment]
@rdbende any updates on the new release, this is a big roadblock for running on MacOS?
